new Vue({
    el:'#root',
    data:{
        datas:[
            {
                id:1,
                title:'疾风剑豪'
            },
            {
                id:2,
                title:'影流之主'
            },
            {
                id:3,
                title:'放逐之刃'
            },
            {
                id:4,
                title:'发条魔灵'
            },
            {
                id:5,
                title:'黑暗之女'
            }
        ],
        state:false,
        title:''
    },
    methods:{
        aa(){
            this.state=true;
        },
        bb(val){
            this.title=val;
            this.state=false;
        }
    }
})